name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # First job: check if test scripts exist
  check-tests:
    name: Check for Tests
    runs-on: self-hosted
    outputs:
      tests_exist: ${{ steps.check.outputs.tests_exist }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check for test files
        id: check
        run: |
          # Look for test files in the repository and redirect stderr to napaka.txt
          find . -name "*test*.cpp" -o -name "*Test*.cpp" 2> napaka.txt
          
          # Check if tests were found
          if find . -name "*test*.cpp" -o -name "*Test*.cpp" | grep -q .; then
            echo "Tests found in the repository"
            echo "tests_exist=true" >> $GITHUB_OUTPUT
          else
            echo "No tests found in the repository"
            echo "tests_exist=false" >> $GITHUB_OUTPUT
            exit 1
          fi
  
      - name: Save error log
        uses: actions/upload-artifact@v2
        with:
          name: error-logs
          path: napaka.txt
          retention-days: 7

  # Second job: run tests
  run-tests:
    name: Run Tests
    needs: check-tests
    runs-on: self-hosted
    if: ${{ needs.check-tests.outputs.tests_exist == 'true' }}
    
    # Matrix strategy for different build types
    strategy:
      matrix:
        build_type: [Debug, Release]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check for error log
        run: |
          if [ -f artifacts/napaka.txt ]; then
            echo "Content of napaka.txt:"
            cat artifacts/napaka.txt
          else
            echo "Error log not found"
          fi
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgtest-dev
      
      - name: Configure and build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          make
      
      - name: Run tests
        working-directory: build
        run: ctest --verbose
